on: [push]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checks out Branch
        uses: actions/checkout@v3

      - name: Install Hardhat
        run: npm install

      - name: Run tests
        run: npx hardhat test
